//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competencia
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public short Tempo { get; set; }
    
        public virtual Tarefa Tarefa { get; set; }
        public virtual Analista Analista { get; set; }
    }
}
